# Generated by Django 4.0.1 on 2022-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('specility', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('clinic_address', models.TextField()),
                ('dob', models.DateField()),
                ('reg_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
