# Generated by Django 4.0.1 on 2022-01-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='physician',
        ),
    ]
