# Generated by Django 4.0.1 on 2022-01-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctor_physician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='email',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='reg_time',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='specility',
        ),
    ]
