# Generated by Django 4.0 on 2022-01-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_demotable'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('specility', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('clinic_address', models.TextField()),
                ('dob', models.DateField()),
                ('reg_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='demotable',
        ),
    ]
