# Generated by Django 4.0 on 2022-01-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_doctors_dob_remove_doctors_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
