# Generated by Django 4.0 on 2022-01-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_delete_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('specility', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=1000)),
                ('gender', models.TextField()),
                ('clinic_address', models.TextField()),
                ('reg_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
