# Generated by Django 4.0 on 2022-01-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='specility',
            new_name='specality',
        ),
    ]
